### ISSUE TITLE
Win Server 2019 : Brotli compression InProcess extreme memory usage

### ISSUE THREAD

**Issue by dylanvdmerwe** [microsoft/IIS.Compression#41] opened 2020-06-10 19:58 UTC
A long thread has been detailed [here ](https://github.com/dotnet/aspnetcore/issues/21344) where it was found that the Microsoft IIS Compression module that enabled brotli compression causes a runaway memory usage issue. 

This occurs with a netcore app (tested on 2.0, 3.0 and 3.1) running with `InProcess` enabled, so through `w3wp.exe` and is observed on Server 2019.

> I used fiddler to find the difference is in the requests, between IE and Edge Chromium.
> Edge: Accept-Encoding: gzip, deflate, _**br**_
> IE: Accept-Encoding: gzip, deflate
> So, brotli (_iisbrotli.dll_), IIS Compression Module is the problem and it is working fine after uninstalling it.

**Comment by bangbingsyb** [comment] 2020-06-14 23:34
@dylanvdmerwe  Thanks for letting us know the potential memory leak. We are looking into it and try to reproduce the problem on our side. Meanswhile, is it possible for you to provide us a mini app to show the leak? Does it only happen with dynamic compression?

**Comment by balajigunasekaran** [comment] 2020-06-15 23:41
```cs
public class Startup
{
    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.UseRouting();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapGet("/", async context =>
            {
                context.Response.Headers.Add(
                    "Content-Type", 
                    new StringValues("application/javascript"));
                await Task.CompletedTask;
            });
        });
    }
}
```
After a lot of combinations, narrowed down our large piece of cod, to above one, which can reproduce this issue. Its a simple netcore webapplication, which you have to publish and deploy it as Site in IIS (IIS Compression module should be installed & enabled :P). The issue is that, during no content scenario, iiszlib is going into a infinite recursive loop.

Tested it with this configuration in **_applicationhost.config_**. When executing requests with _Accept-Encoding_ value as , _br_ and _gzip1_ works fine. But when tried with _gzip_, it ran into infinite loop.
```xml
<httpCompression directory="%SystemDrive%\inetpub\temp\IIS Temporary Compressed Files">
        <scheme name="br" dll="%ProgramFiles%\IIS\IIS Compression\iisbrotli.dll" />
        <scheme name="gzip" dll="%ProgramFiles%\IIS\IIS Compression\iiszlib.dll" />
	<scheme name="gzip1" dll="%windir%\system32\inetsrv\gzip.dll" />
</httpCompression>
```
Curious on this, I wanted to give some extra diagnosis information and headstart to the next person. I havent worked with c++ code before, so sorry if the below analysis or diagnosis is wrong.
I cloned this repo and found that _Compress2_ method is called and in that, _deflate()_ call is returning _**-5(Z_BUF_ERROR)**_, even when stream's s->pending = 0. And with this value as -5 and pending = 0, I press F5 then infinite looping started, by calling compress2 method again and again.

_IIS.Compression\iiszlib\iiszlib.cxx_
```c
HRESULT WINAPI
Compress2(...) {
...

ret = deflate(&pContext->_strm, flushMode);

    if (ret == Z_OK)
    {
...
    }
    else if (ret == Z_BUF_ERROR)
    {
        DBGINFO((DBG_CONTEXT, "Need to call Compress2 again\n"));//Line #: 404 
       //Infinite loop because compress2 is called recursively again and again

        hr = S_OK;
    }
```
I thought that might be the issue, patched some code below in _deflate.c_ and found that it is working after that. I am not confident whether my code is proper fix, so I will just pass this information to the next person. Anyway below is the fix, which I tried, built and tested it to be working fine.

_IIS.Compression\submodules\zlib\deflate.c_

```c
if (s->pending != 0) {
...
   } else if (strm->avail_in == 0 && RANK(flush) <= RANK(old_flush) &&
               flush != Z_FINISH) {
       //ERR_RETURN(strm, Z_BUF_ERROR); //Old code, Line #: 805
       ERR_RETURN(strm, s->pending != 0 ? Z_BUF_ERROR : Z_STREAM_END);
    }
```
Please let me know if further details are required. Sorry if the post is very long.

**Comment by bangbingsyb** [comment] 2020-06-17 01:00
@balajigunasekaran Thanks for your awesome investigation. I think it helps significantly to narrow down the issue. I will play with it on my side.

Just to further clarify a few things:

1. In your scenario, what is the outcome of the observed infinite loops? Was it showed as unbounded memory growth? Did the request fail eventually?
2. Based on your explanation, the problematic extension is iiszlib.dll instead of iisbrotli? I saw iisbrotli was reported [here ](https://github.com/dotnet/aspnetcore/issues/21344) as the problematic extension?

deflate.c is inside the submodule we grab from the original zlib library: https://github.com/madler/zlib

We may be able to fix the problem in our code path.

**Comment by balajigunasekaran** [comment] 2020-06-17 05:02
Just to further clarify a few things:

In your scenario, what is the outcome of the observed infinite loops? Was it shown as unbounded memory growth? Did the request fail eventually?
**Yes unbound memory growth, within a few seconds. My PC hanged within a minute. Request didn't fail immediately, it failed only after I force kill w3wp.**

Based on your explanation, the problematic extension is iiszlib.dll instead of iisbrotli? I saw iisbrotli was reported here as the problematic extension?
**Issue is there only when I pass _gzip_ as _Accept-Encoding_ header. _br_ just works fine.
Here is my comments on that post also posted a screen recording there in that thread.
https://github.com/dotnet/aspnetcore/issues/21344#issuecomment-641092124**

**Comment by dylanvdmerwe** [comment] 2020-07-28 08:38
I wanted to find out if there is anything else needed in order to help diagnose this issue?

**Comment by bangbingsyb** [comment] 2020-08-06 19:21
@dylanvdmerwe Sorry for the late reply - I was in my parental leave in the past 6 weeks and just came back to work :) Nope. I think the repo steps are clear enough for me to understand the root cause and fix.

**Comment by mazuryv** [comment] 2020-08-18 10:25
Hello.
I found this problem with IIS Windows Server Version 1809, %ProgramFiles%\IIS\IIS Compression\iiszlib.dll.
My server send Content-Type: text/plain after API Get request. Content is GUID as string. 
Compression creates many memory frames which fills all private and virtual memory.
I caught one.
![image](https://user-images.githubusercontent.com/26767342/90502282-3de3d580-e156-11ea-99e8-a82590268820.png)
Brotli works well.

**Comment by mr-le** [comment] 2020-09-30 01:16
I had same problem after installing the brotli module my server hanged, could not even connect through remote desktop, had to reboot it via IPMI. stopped IIS , removed it and everything works normal.
Installed brotli module from this guy https://github.com/saucecontrol/Brotli-IIS and no problems so far.

**Comment by jhkimnew** [comment] 2020-10-07 21:18
This issue is understood and working to fix the problem. 
https://github.com/microsoft/IIS.Compression/pull/44

**Comment by bangbingsyb** [comment] 2020-10-19 20:03
@dylanvdmerwe @balajigunasekaran @mr-le @mazuryv 

The fix has been merged and we will release the new bits with the fix soon. 

Meanwhile, since the root cause came from the behavior of zlib library for gzip, as a quick workaround you can still use the brotli extension installed in the bundle (iisbrotli.dll) for brotli compression, and at the same time use the inbox gzip extension (gzip.dll) instead for gzip compression.

Here is the httpCompression configuration section in applicationHost.config:

<httpCompression directory="%SystemDrive%\inetpub\temp\IIS Temporary Compressed Files">
    <scheme name="br" dll="%ProgramFiles%\IIS\IIS Compression\iisbrotli.dll" />
    **<scheme name="gzip" dll="%windir%\system32\inetsrv\gzip.dll" />**
    <dynamicTypes>
        <add mimeType="text/*" enabled="true" />
        <add mimeType="message/*" enabled="true" />
        <add mimeType="application/x-javascript" enabled="true" />
        <add mimeType="application/javascript" enabled="true" />
        <add mimeType="*/*" enabled="false" />
    </dynamicTypes>
    <staticTypes>
        <add mimeType="text/*" enabled="true" />
        <add mimeType="message/*" enabled="true" />
        <add mimeType="application/javascript" enabled="true" />
        <add mimeType="application/atom+xml" enabled="true" />
        <add mimeType="application/xaml+xml" enabled="true" />
        <add mimeType="image/svg+xml" enabled="true" />
        <add mimeType="*/*" enabled="false" />
    </staticTypes>
</httpCompression>

**Comment by dylanvdmerwe** [comment] 2020-11-12 19:57
Any idea on when this will be released?

**Comment by glat** [comment] 2020-11-21 07:37
+1 We need a new release.

**Comment by dylanvdmerwe** [comment] 2021-01-07 19:20
Please advise when a new release will be made with this fix?

**Comment by jhkimnew** [comment] 2021-01-16 03:42
https://github.com/microsoft/IIS.Compression/releases/tag/v1.0.5113

**Closed by jhkimnew** 2021-01-16 03:42 UTC
Labels: bug

**Comment by 1265578519** [comment] 2023-12-11 11:51
我使用Windows2022，w3wp.exe有相同的13GB高占用内存问题，我没有安装br模块
